{% set version = "1.3.35" %}

package:
  name: graphicsmagick
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/{{ version }}/GraphicsMagick-{{ version }}.tar.bz2
    sha256: 7fd0b49903eb35df4ab5ca76139ab3f023f47485a4913fbdcf5c642c6e5f01fc
  - path: CMakeLists.txt

build:
  number: 0
  # ghostscript and gnuplot not available
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - ninja  # [win]
  host:
    - bzip2
    - jpeg
    - libpng
    - freetype
    - libtiff
    - zlib
    - ghostscript  # [unix]
    - gnuplot  # [unix]
    - libwebp  # [unix]
    - libxml2  # [unix]
    - zstd  # [unix]
    - xorg-libsm  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxdmcp  # [linux]
    - xorg-libxau  # [linux]
    - libgomp      # [linux]
    - xz  # [linux]

  run:
    - bzip2  # [unix]
    - jpeg  # [unix]
    - libpng
    - freetype
    - libtiff
    - zlib
    - ghostscript  # [unix]
    - gnuplot  # [unix]
    - libwebp  # [unix]
    - libxml2  # [unix]
    - zstd  # [unix]
    - xorg-libsm  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libice  # [linux]
    - libgomp      # [linux]
    - xz  # [linux]

test:
  commands:
    - gm -help
    - if not exist %LIBRARY_PREFIX%\\bin\\GraphicsMagick.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\GraphicsMagick++.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\GraphicsMagickWand.dll exit 1  # [win]

about:
  home: http://www.graphicsmagick.org/
  license: MIT
  license_file: Copyright.txt
  summary: GraphicsMagick is the swiss army knife of image processing

extra:
  recipe-maintainers:
    - bgruening
    - seanyen
