{% set version = "1.3.35" %}

package:
  name: graphicsmagick
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/{{ version }}/GraphicsMagick-{{ version }}.tar.bz2
  sha256: 7fd0b49903eb35df4ab5ca76139ab3f023f47485a4913fbdcf5c642c6e5f01fc

build:
  number: 0
  # ghostscript and gnuplot not available
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ghostscript
    - libpng
    - gnuplot
    - xorg-libsm
    - libwebp
    - freetype
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libxau
    - libtiff
    - jpeg
    - bzip2
    - libxml2
    - xz
    - zlib
  run:
    - ghostscript
    - libpng
    - gnuplot
    - xorg-libsm
    - libwebp
    - freetype
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libxau
    - xorg-libx11
    - libtiff
    - jpeg
    - bzip2
    - libxml2
    - xz
    - zlib

test:
  commands:
    - gm -help

about:
  home: http://www.graphicsmagick.org/
  license: MIT
  license_file: Copyright.txt
  summary: GraphicsMagick is the swiss army knife of image processing

extra:
  recipe-maintainers:
    - bgruening
