{% set version = "1.3.40" %}

package:
  name: graphicsmagick
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/{{ version }}/GraphicsMagick-{{ version }}.tar.bz2
    sha256: 7312bdf763f21e29b36fb0bdc063e9911f146e9111b480a60e9ba959e73bdbd2
    patches:
      - windows.patch  # [win]
  - path: CMakeLists.txt  # [win]

build:
  number: 1

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - ninja  # [win]
    - make  # [unix]
  host:
    - bzip2
    - libjpeg-turbo
    - libpng
    - freetype
    - libtiff
    - zlib
    - ghostscript  # [unix]
    - gnuplot  # [unix]
    - libwebp  # [unix]
    - libxml2  # [unix]
    - zstd  # [unix]
    - xorg-libsm  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxdmcp  # [linux]
    - xorg-libxau  # [linux]
    - libgomp      # [linux]
    - xz  # [linux]

  run:
    - bzip2  # [unix]
    - libjpeg-turbo   # [unix]
    - libpng
    - freetype
    - libtiff
    - zlib
    - ghostscript  # [unix]
    - gnuplot  # [unix]
    - libwebp  # [unix]
    - libxml2  # [unix]
    - zstd  # [unix]
    - xorg-libsm  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libice  # [linux]
    - xz  # [linux]

test:
  commands:
    - gm -help
    - if not exist %LIBRARY_PREFIX%\\bin\\GraphicsMagick.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\GraphicsMagick++.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\GraphicsMagickWand.dll exit 1  # [win]

about:
  home: http://www.graphicsmagick.org/
  license: MIT
  license_file: Copyright.txt
  summary: GraphicsMagick is the swiss army knife of image processing

extra:
  recipe-maintainers:
    - bgruening
    - seanyen
    - ocefpaf
